require: rubocop-rails

Style/StringLiterals:
    Enabled: true
    EnforcedStyle: double_quotes

Metrics/BlockLength:
    Enabled: false

Metrics/MethodLength:
    Enabled: false

Documentation:
  Enabled: false

Layout/LineLength:
    Max: 1000

Style/ClassAndModuleChildren:
    Enabled: false

Style/EmptyMethod:
    Enabled: false